data_stores:
  root :  "C:/Users/bmoha/Work/datasets/commonlit-evaluate-student-summaries/"
  train_base: "train_base.parquet"
  train_static_cb_0: "train_static_cb_0.parquet"
  train_static_0: "train_static_0_*.parquet"
  train_applprev_1: "train_applprev_1_*.parquet"
  train_tax_registry_a_1 : "train_tax_registry_a_1.parquet"
  train_tax_registry_b_1 : "train_tax_registry_b_1.parquet"
  train_tax_registry_c_1 : "train_tax_registry_c_1.parquet"
  train_credit_bureau_a_1 : "train_credit_bureau_a_1_*.parquet"
  train_credit_bureau_b_1 : "train_credit_bureau_b_1.parquet"
  train_other_1: "train_other_1.parquet"
  train_person_1 : "train_person_1.parquet"
  train_deposit_1 : "train_deposit_1.parquet"
  train_debitcard_1 : "train_debitcard_1.parquet"
  train_credit_bureau_b_2 : "train_credit_bureau_b_2.parquet"
  train_credit_bureau_a_2 : "train_credit_bureau_a_2_*.parquet"
  train_applprev_2 : "train_applprev_2.parquet"
  train_person_2 : "train_person_2.parquet"